name: 'Build Vacuum'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository with submodules'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Set up Java Development Kit'
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 20
      - name: 'Bootstrap Bach'
        run: java .bach/src/run.bach/run/bach/Bootstrap.java
      - name: 'Build Vacuum with Bach'
        run: java @bach build
